<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gkama.AuthApi\Gkama.AuthApi.csproj" />
    <ProjectReference Include="..\Gkama.BusinessApi\Gkama.BusinessApi.csproj" />
  </ItemGroup>

</Project>
